"""Plotting module for DifferentialLab."""

from plotting.plot_utils import (
    _apply_plot_style,
    _finalize_plot,
    create_contour_plot,
    create_energy_evolution_plot,
    create_energy_per_mode_plot,
    create_image_animation_plot,
    create_line_animation_plot,
    create_phase_3d_plot,
    create_phase_plot,
    create_polar_contour_plot,
    create_solution_plot,
    create_surface_animation_plot,
    create_surface_plot,
    create_vector_animation_3d,
    create_vector_animation_plot,
    create_vector_field_plot,
    export_animated_figure_to_mp4,
    export_animation_to_mp4,
)

__all__ = [
    "_apply_plot_style",
    "_finalize_plot",
    "create_contour_plot",
    "create_polar_contour_plot",
    "create_energy_evolution_plot",
    "create_energy_per_mode_plot",
    "create_image_animation_plot",
    "create_line_animation_plot",
    "create_phase_3d_plot",
    "create_phase_plot",
    "create_solution_plot",
    "create_surface_plot",
    "create_surface_animation_plot",
    "create_vector_field_plot",
    "create_vector_animation_3d",
    "create_vector_animation_plot",
    "export_animation_to_mp4",
    "export_animated_figure_to_mp4",
]
